### ISSUE TITLE
Webpage is flaky during the weekends

### ISSUE THREAD

**Issue by Algunenano** [ClickHouse/aretestsgreenyet#4]
:smile: 

![image](https://github.com/ClickHouse/aretestsgreenyet/assets/664253/3f2222b8-3279-4423-95d6-7b560d67932c)

Everything according to the query is green but [this check](https://github.com/ClickHouse/aretestsgreenyet/blob/f4fb48e5e068e68d300b9aedec5303c73bd98a79/index.html#L200) prevents it from being shown green.

I guess that Sunday's have lower amount of tests. Maybe it should say so if the result is ok but there weren't enough runs to confirm

**Comment by alexey-milovidov** [comment]
We need to merge more PRs on Sundays.
